# Generated by Django 4.2.17 on 2025-12-19 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0003_alter_tag_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "tag")},
        ),
    ]
