# Generated by Django 4.2.27 on 2026-03-13 02:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEmailPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_all_emails", models.BooleanField(default=True)),
                ("allow_notification", models.BooleanField(default=True)),
                ("allow_promotional", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mailer_user_email_preference",
            },
        ),
        migrations.CreateModel(
            name="EmailQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                (
                    "from_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body_html", models.TextField()),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                            ("payment_notification", "Payment Notification"),
                            ("generic", "Generic"),
                        ],
                        default="generic",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("notification", "Notification"),
                            ("promotional", "Promotional"),
                        ],
                        default="transactional",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "skip_reason",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("context_data", models.JSONField(blank=True, default=dict)),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mailer_email_queue",
                "ordering": ["priority", "scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="idx_email_status_scheduled",
                    ),
                    models.Index(
                        fields=["priority", "scheduled_at"],
                        name="idx_email_priority_scheduled",
                    ),
                ],
            },
        ),
    ]
