# Generated by Django 3.2.9 on 2022-06-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetexture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDOClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('abbreviation', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
