# Generated by Django 3.2.9 on 2022-07-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetexture', '0002_bdoclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdoclass',
            name='image',
            field=models.ImageField(default=None, upload_to='bdoclass/'),
        ),
    ]
