# Generated by Django 4.2 on 2023-06-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facetexture', '0006_bdoclass_class_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('show', models.BooleanField()),
                ('image', models.CharField(max_length=64)),
                ('order', models.IntegerField()),
                ('upload', models.BooleanField()),
                ('bdoClass', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='facetexture.bdoclass')),
                ('facetexture', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='facetexture.facetexture')),
            ],
        ),
    ]
