# Generated by Django 4.2 on 2023-07-20 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facetexture', '0008_alter_character_image_alter_character_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='facetexture',
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
