# Generated by Django 4.2.17 on 2025-12-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
