# Generated by Django 4.2.17 on 2025-12-16 03:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_payment_description_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_type', models.IntegerField(choices=[(0, 'credit'), (1, 'debit')])),
                ('raw_name', models.TextField(max_length=255)),
                ('raw_description', models.TextField(blank=True, max_length=1024)),
                ('raw_reference', models.TextField(blank=True, max_length=1024)),
                ('raw_date', models.DateField()),
                ('raw_installments', models.IntegerField()),
                ('raw_payment_date', models.DateField()),
                ('raw_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('import_type', models.IntegerField(choices=[(0, 'merge'), (1, 'split'), (2, 'new')])),
                ('merge_group', models.TextField(blank=True, max_length=255)),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_imported_payment',
            },
        ),
    ]
