# Generated by Django 4.2.17 on 2025-12-17 15:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0002_alter_tag_user'),
        ('payment', '0003_payment_description_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_source', models.CharField(choices=[('transactions', 'Transactions'), ('card_payments', 'Card payments')], max_length=32)),
                ('import_strategy', models.CharField(choices=[('merge', 'Merge'), ('split', 'Split'), ('new', 'New')], max_length=16)),
                ('reference', models.TextField(blank=True, max_length=1024)),
                ('merge_group', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('raw_type', models.IntegerField(choices=[(0, 'credit'), (1, 'debit')])),
                ('raw_name', models.TextField(max_length=255)),
                ('raw_description', models.TextField(blank=True, max_length=1024)),
                ('raw_date', models.DateField()),
                ('raw_installments', models.IntegerField()),
                ('raw_payment_date', models.DateField()),
                ('raw_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
                ('raw_tags', models.ManyToManyField(blank=True, related_name='imported_payment', to='tag.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_imported_payment',
            },
        ),
        migrations.AddConstraint(
            model_name='importedpayment',
            constraint=models.UniqueConstraint(fields=('reference', 'user'), name='uniq_imported_payment_reference_user'),
        ),
    ]
