# Generated by Django 4.2.27 on 2025-12-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_importedpayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedpayment",
            name="status_description",
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
