# Generated by Django 4.2.17 on 2025-12-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_importedpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedpayment',
            name='merge_group',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
