# Generated by Django 4.2.17 on 2025-12-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_importedpayment_merge_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedpayment',
            name='raw_reference',
            field=models.TextField(blank=True, max_length=1024, unique=True),
        ),
    ]
