# Generated by Django 4.2.27 on 2026-03-13 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_importedpayment_status_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importedpayment",
            name="raw_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="importedpayment",
            name="raw_installments",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="importedpayment",
            name="raw_name",
            field=models.TextField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="importedpayment",
            name="raw_payment_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="importedpayment",
            name="raw_type",
            field=models.IntegerField(choices=[(0, "credit"), (1, "debit")], default=1),
        ),
    ]
