# Generated by Django 4.2.27 on 2026-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_importedpayment_raw_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedpayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
