# Generated by Django 4.2.17 on 2025-12-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_importedpayment_raw_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importedpayment',
            old_name='raw_reference',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='importedpayment',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'failed')], default=0),
        ),
    ]
