# Generated by Django 4.2.17 on 2025-12-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_user'),
        ('payment', '0007_rename_raw_reference_importedpayment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedpayment',
            name='raw_tags',
            field=models.ManyToManyField(blank=True, related_name='imported_payment', to='tag.tag'),
        ),
        migrations.AlterField(
            model_name='importedpayment',
            name='reference',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='importedpayment',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'queued'), (2, 'processing'), (3, 'completed'), (4, 'failed')], default=0),
        ),
        migrations.AddConstraint(
            model_name='importedpayment',
            constraint=models.UniqueConstraint(fields=('reference', 'user'), name='uniq_imported_payment_reference_user'),
        ),
    ]
