# Generated by Django 4.2.7 on 2024-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_question_text_alter_answer_dislike_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_details',
            field=models.TextField(default=''),
        ),
    ]
