# Generated by Django 4.2.7 on 2024-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_question_question_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='combat_style',
            field=models.IntegerField(choices=[(0, 'Despertar'), (1, 'Sucessão')], default=0, null=True),
        ),
    ]
