# Generated by Django 4.2.7 on 2024-06-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0005_path_date_path_alter_answer_combat_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='date_path',
            field=models.DateField(null=True),
        ),
    ]
