# Generated by Django 4.2.7 on 2024-06-24 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facetexture', '0011_character_active'),
        ('classification', '0006_alter_path_date_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AnswerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combat_style', models.IntegerField(choices=[(1, 'Despertar'), (2, 'Sucessão')], default=1, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('vote', models.FloatField(default=0)),
                ('bdo_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facetexture.bdoclass')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.question')),
            ],
        ),
    ]
