# Generated by Django 4.2.7 on 2024-06-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0007_answer_updated_at_answersummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersummary',
            name='combat_style',
        ),
        migrations.RemoveField(
            model_name='answersummary',
            name='vote',
        ),
        migrations.AddField(
            model_name='answersummary',
            name='resume',
            field=models.JSONField(default=dict),
        ),
    ]
