# Generated by Django 4.2.7 on 2024-06-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0008_remove_answersummary_combat_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersummary',
            name='question',
        ),
    ]
