# Generated by Django 4.2.15 on 2025-01-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'empty'), (1, 'projection'), (2, 'calculated'), (3, 'accounted')], default=0)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
