# Generated by Django 3.2.9 on 2022-09-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_auto_20220907_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.IntegerField(choices=[(0, 'credit'), (1, 'debit')], default=0),
        ),
    ]
