# Generated by Django 3.2.9 on 2022-09-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tags',
            field=models.ManyToManyField(to='financial.Tag'),
        ),
    ]
