# Generated by Django 3.2.9 on 2022-09-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_invoice_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
