# Generated by Django 4.2.27 on 2026-03-01 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Auth"),
                            ("financial", "Financial"),
                            ("facetexture", "Facetexture"),
                            ("classification", "Classification"),
                            ("remote", "Remote"),
                            ("pusher", "Pusher"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("error", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("path", models.CharField(blank=True, default="", max_length=500)),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=100)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="audit_log_created_e49a79_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_log_user_id_b57afc_idx",
                    ),
                    models.Index(fields=["action"], name="audit_log_action_b32d4d_idx"),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="audit_log_categor_ba4a92_idx",
                    ),
                ],
            },
        ),
    ]
