# Generated by Django 4.2.27 on 2026-03-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseScriptExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_version", models.CharField(max_length=20)),
                ("script_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                ("output", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "release_script_execution",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["release_version", "script_name"],
                        name="release_scr_release_a1ed7d_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="release_scr_status_d2b1bd_idx",
                    ),
                ],
            },
        ),
    ]
