"""
Django settings for kawori project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.admin",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework_simplejwt",
    "contract",
    "invoice",
    "payment",
    "tag",
    "financial",
    "remote",
    "pusher_webhook",
    "authentication",
    "discord",
    "facetexture",
    "classification",
    "user_profile",
    "analytics",
    "budget",
    "audit",
    "mailer",
    "ai",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "kawori.middleware.CsrfCookieOnlyMiddleware",
    "kawori.middleware.SimpleCorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]


ROOT_URLCONF = "kawori.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kawori.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation." "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation." "MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation." "CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation." "NumericPasswordValidator",
    },
]

# Rest framework config

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
}

# JWT

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(weeks=4),
    "ALGORITHM": "HS256",
}
ACCESS_TOKEN_NAME = "access_token"  # nosec B105
REFRESH_TOKEN_NAME = "refresh_token"  # nosec B105

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

PROJECT_ROOT = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(PROJECT_ROOT, "../.."))

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATIC_URL = "/static/"
RELEASE_SCRIPT_REGISTRY_PATH = BASE_DIR / "scripts.xml"

ENV_PUSHER_APP_ID = ""
ENV_PUSHER_KEY = ""
ENV_PUSHER_SECRET = ""  # nosec B105
ENV_PUSHER_CLUSTER = ""

# ========== Google Cloud Storage ==========
GS_BUCKET_NAME = ""
GS_CREDENTIAL_PATH = "credentials.json"
GS_STORAGE_URL = "https://storage.googleapis.com"

# ========== CSRF ==========
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = "Lax"

# ========== CORS ==========
CORS_ALLOW_CREDENTIALS = True

# ========== EMAIL CONFIGURATION ==========
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Email para receber notificações
NOTIFICATION_EMAIL = os.environ.get('NOTIFICATION_EMAIL', EMAIL_HOST_USER)

# ========== MAILER ==========
MAILER_GLOBAL_ENABLED = True

# ========== SOCIAL AUTH ==========
SOCIAL_AUTH_STATE_EXPIRATION_MINUTES = int(os.environ.get("SOCIAL_AUTH_STATE_EXPIRATION_MINUTES", "10"))
SOCIAL_AUTH_PROVIDERS = {
    "google": {
        "client_id": os.environ.get("SOCIAL_GOOGLE_CLIENT_ID", ""),
        "client_secret": os.environ.get("SOCIAL_GOOGLE_CLIENT_SECRET", ""),
    },
    "discord": {
        "client_id": os.environ.get("SOCIAL_DISCORD_CLIENT_ID", ""),
        "client_secret": os.environ.get("SOCIAL_DISCORD_CLIENT_SECRET", ""),
    },
    "github": {
        "client_id": os.environ.get("SOCIAL_GITHUB_CLIENT_ID", ""),
        "client_secret": os.environ.get("SOCIAL_GITHUB_CLIENT_SECRET", ""),
    },
    "facebook": {
        "client_id": os.environ.get("SOCIAL_FACEBOOK_CLIENT_ID", ""),
        "client_secret": os.environ.get("SOCIAL_FACEBOOK_CLIENT_SECRET", ""),
    },
    "microsoft": {
        "client_id": os.environ.get("SOCIAL_MICROSOFT_CLIENT_ID", ""),
        "client_secret": os.environ.get("SOCIAL_MICROSOFT_CLIENT_SECRET", ""),
    },
}

# ========== AI / LLM ==========
AI_DEFAULT_TIMEOUT_SECONDS = int(os.environ.get("AI_DEFAULT_TIMEOUT_SECONDS", "20"))
AI_DEFAULT_MAX_RETRIES = int(os.environ.get("AI_DEFAULT_MAX_RETRIES", "1"))
AI_ENABLE_FALLBACK = os.environ.get("AI_ENABLE_FALLBACK", "true").lower() == "true"
AI_ASSIST_ENABLED = os.environ.get("AI_ASSIST_ENABLED", "true").lower() == "true"
AI_IMPORT_SUGGESTION_MAX_ITEMS = int(os.environ.get("AI_IMPORT_SUGGESTION_MAX_ITEMS", "20"))
AI_FEATURE_FLAGS = {
    "payment_reconciliation": os.environ.get("AI_FEATURE_PAYMENT_RECONCILIATION", "true"),
    "payment_normalization": os.environ.get("AI_FEATURE_PAYMENT_NORMALIZATION", "true"),
    "audit_insights": os.environ.get("AI_FEATURE_AUDIT_INSIGHTS", "true"),
    "release_compliance": os.environ.get("AI_FEATURE_RELEASE_COMPLIANCE", "true"),
    "regression_tests": os.environ.get("AI_FEATURE_REGRESSION_TESTS", "true"),
    "communication_notifications": os.environ.get("AI_FEATURE_COMMUNICATION_NOTIFICATIONS", "true"),
}

AI_PROVIDERS = {
    "openai": {
        "engine": "openai",
        "api_key": os.environ.get("OPENAI_API_KEY", ""),
        "base_url": os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1"),
    },
    "anthropic": {
        "engine": "anthropic",
        "api_key": os.environ.get("ANTHROPIC_API_KEY", ""),
        "base_url": os.environ.get("ANTHROPIC_BASE_URL", "https://api.anthropic.com/v1"),
        "api_version": os.environ.get("ANTHROPIC_API_VERSION", "2023-06-01"),
    },
}

AI_TASK_ROUTES = {
    "default": {
        "primary": {
            "provider": os.environ.get("AI_DEFAULT_PROVIDER", "openai"),
            "model": os.environ.get("AI_MODEL_DEFAULT", "gpt-4o-mini"),
        },
        "fallbacks": [
            {
                "provider": os.environ.get("AI_DEFAULT_FALLBACK_PROVIDER", "anthropic"),
                "model": os.environ.get("AI_MODEL_DEFAULT_FALLBACK", "claude-3-5-haiku-latest"),
            }
        ],
        "timeout_seconds": AI_DEFAULT_TIMEOUT_SECONDS,
        "max_retries": AI_DEFAULT_MAX_RETRIES,
    },
    "text_generation": {
        "primary": {"provider": "openai", "model": os.environ.get("AI_MODEL_TEXT_GENERATION", "gpt-4o-mini")},
        "fallbacks": [
            {"provider": "anthropic", "model": os.environ.get("AI_MODEL_TEXT_GENERATION_FALLBACK", "claude-3-5-haiku-latest")}
        ],
        "timeout_seconds": AI_DEFAULT_TIMEOUT_SECONDS,
        "max_retries": AI_DEFAULT_MAX_RETRIES,
    },
    "summarization": {
        "primary": {"provider": "openai", "model": os.environ.get("AI_MODEL_SUMMARIZATION", "gpt-4o-mini")},
        "fallbacks": [
            {"provider": "anthropic", "model": os.environ.get("AI_MODEL_SUMMARIZATION_FALLBACK", "claude-3-5-haiku-latest")}
        ],
        "timeout_seconds": AI_DEFAULT_TIMEOUT_SECONDS,
        "max_retries": AI_DEFAULT_MAX_RETRIES,
    },
    "classification": {
        "primary": {"provider": "openai", "model": os.environ.get("AI_MODEL_CLASSIFICATION", "gpt-4o-mini")},
        "fallbacks": [
            {"provider": "anthropic", "model": os.environ.get("AI_MODEL_CLASSIFICATION_FALLBACK", "claude-3-5-haiku-latest")}
        ],
        "timeout_seconds": AI_DEFAULT_TIMEOUT_SECONDS,
        "max_retries": AI_DEFAULT_MAX_RETRIES,
    },
    "structured_extraction": {
        "primary": {"provider": "openai", "model": os.environ.get("AI_MODEL_EXTRACTION", "gpt-4o-mini")},
        "fallbacks": [
            {"provider": "anthropic", "model": os.environ.get("AI_MODEL_EXTRACTION_FALLBACK", "claude-3-5-haiku-latest")}
        ],
        "timeout_seconds": AI_DEFAULT_TIMEOUT_SECONDS,
        "max_retries": AI_DEFAULT_MAX_RETRIES,
    },
    "simple_task": {
        "primary": {"provider": "openai", "model": os.environ.get("AI_MODEL_SIMPLE_TASK", "gpt-4o-mini")},
        "fallbacks": [
            {"provider": "anthropic", "model": os.environ.get("AI_MODEL_SIMPLE_TASK_FALLBACK", "claude-3-5-haiku-latest")}
        ],
        "timeout_seconds": AI_DEFAULT_TIMEOUT_SECONDS,
        "max_retries": AI_DEFAULT_MAX_RETRIES,
    },
    "complex_task": {
        "primary": {"provider": "openai", "model": os.environ.get("AI_MODEL_COMPLEX_TASK", "gpt-4o")},
        "fallbacks": [
            {"provider": "anthropic", "model": os.environ.get("AI_MODEL_COMPLEX_TASK_FALLBACK", "claude-3-7-sonnet-latest")}
        ],
        "timeout_seconds": AI_DEFAULT_TIMEOUT_SECONDS,
        "max_retries": AI_DEFAULT_MAX_RETRIES,
    },
}
