# Generated by Django 3.2.9 on 2022-09-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_auto_20220911_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
        ),
    ]
