# Generated by Django 4.2.27 on 2026-03-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128)),
                (
                    "environment",
                    models.CharField(db_index=True, default="all", max_length=32),
                ),
                ("content", models.TextField()),
                ("task_type", models.CharField(max_length=64)),
                ("schema_json", models.JSONField(blank=True, default=dict)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("version", models.CharField(default="v1", max_length=32)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_prompt_override_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_prompt_override",
                "ordering": ["key", "environment", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptOverrideHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("environment", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("task_type", models.CharField(max_length=64)),
                ("schema_json", models.JSONField(blank=True, default=dict)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("version", models.CharField(default="v1", max_length=32)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True, default="")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_prompt_override_history_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompt_override",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_entries",
                        to="ai.promptoverride",
                    ),
                ),
            ],
            options={
                "db_table": "ai_prompt_override_history",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["key", "environment", "-changed_at"],
                        name="ai_prompt_o_key_b51e33_idx",
                    ),
                    models.Index(
                        fields=["action", "-changed_at"],
                        name="ai_prompt_o_action_775255_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="promptoverride",
            index=models.Index(
                fields=["key", "environment"], name="ai_prompt_o_key_2a3b7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptoverride",
            index=models.Index(
                fields=["key", "environment", "is_active"],
                name="ai_prompt_o_key_ac6f5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptoverride",
            index=models.Index(
                fields=["is_active", "updated_at"],
                name="ai_prompt_o_is_acti_4149a8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="promptoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("key", "environment"),
                name="uniq_ai_prompt_override_active_key_environment",
            ),
        ),
    ]
