# Generated by Django 4.2.29 on 2026-03-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_ai_execution_event_and_budget"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiexecutionevent",
            new_name="ai_executio_created_ebb95f_idx",
            old_name="ai_exec_event_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiexecutionevent",
            new_name="ai_executio_feature_c2ec49_idx",
            old_name="ai_exec_event_feature_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiexecutionevent",
            new_name="ai_executio_trace_i_e6a3a4_idx",
            old_name="ai_exec_event_trace_created_idx",
        ),
    ]
