# Generated by Django 4.2.15 on 2025-01-12 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'open'), (1, 'done')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'credit'), (1, 'debit')], default=0)),
                ('name', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('installments', models.IntegerField(default=1)),
                ('payment_date', models.DateField(null=True)),
                ('fixed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('value_open', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('value_closed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('tags', models.ManyToManyField(to='tag.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_invoice',
            },
        ),
    ]
