# Generated by Django 4.2.17 on 2025-11-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_budgettag'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='tag.tag'),
        ),
    ]
