# Generated by Django 4.2.17 on 2025-11-14 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0002_alter_tag_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="invoices", to="tag.tag"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
