# Generated by Django 4.2.17 on 2025-11-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
        ("invoice", "0002_alter_invoice_tags_alter_invoice_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contract.contract",
            ),
        ),
    ]
