# Generated by Django 4.2.27 on 2025-12-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_alter_invoice_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="type",
            field=models.IntegerField(choices=[(0, "credit"), (1, "debit")], default=1),
        ),
    ]
