# Generated by Django 3.2.9 on 2022-07-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetexture', '0005_previewbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdoclass',
            name='class_image',
            field=models.ImageField(null=True, upload_to='classimage/'),
        ),
    ]
