# Generated by Django 4.2 on 2023-08-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetexture', '0010_alter_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
