# Generated by Django 4.2.7 on 2024-07-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetexture', '0011_character_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdoclass',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
