# Generated by Django 4.2.15 on 2025-01-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetexture', '0012_bdoclass_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdoclass',
            name='class_order',
            field=models.IntegerField(default=1),
        ),
    ]
